language: ruby
script: 'rspec ./spec'
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
notifications:
  recipients:
    - adam@29ways.co.uk
before_script:
  - cd spec/dummy; RAILS_ENV=test rake db:migrate; cd ../..
